default:
    image: python:3.9-slim-bullseye
    before_script:
       - apt-get update
       - apt-get install -y python3-pip
       - pip install -r requirements.txt
stages:
    - test
    - dummy
test:
    script:
        - coverage run -m pytest
        - coverage report
dummy:
    script:
        - echo "Pipeline finished"