default:
    image: python:3.9-slim-bullseye
    before_script:
       - apt-get update
       - apt-get install -y python3-pip
       - pip install -r requirements.txt
stages:
    - test
test:
  script:
    - pip install pytest pytest-cov
    - pytest --cov=. test_hello.py
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml